
services:


  go_db2:
      container_name: go_oms_software
      image: postgres:14
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:  
    pgdata: {}



